version: '3.8'
volumes:
  db_data: {}
  pgadmin:
services:
  traefik:
    image: traefik:latest
    ports:
      - '80:80'
      - '443:443'
    command:
      - '--providers.docker=true'
      - '--providers.docker.swarmmode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web-secure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=web-secure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.letsencryptresolver.acme.email=phillip@golem.network'
      - '--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=swarm-example'
      - 'traefik.http.routers.traefik.middlewares=traefik-compress'

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - swarm-example
  webserver:
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    image: webserver:latest
    depends_on:
      - postgres
    volumes:
      - './stats-monitor:/stats-monitor/'
      - './wait-for-it.sh:/wait-for-it.sh'
    env_file:
      - ./.envs/.django
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.webserver.rule=Host(`status.golemstats.com`)'
        - 'traefik.http.routers.webserver.entrypoints=web'
        - 'traefik.http.services.webserver.loadbalancer.server.port=8002'
        - 'traefik.http.routers.webserver.service=webserver@docker'
        - 'traefik.docker.network=swarm-example'
        - 'traefik.http.middlewares.webserver_compress.compress=true'
        - 'traefik.http.routers.webserver.middlewares=webserver_compress'
        - 'traefik.http.routers.webserver.tls.certresolver=letsencryptresolver'
        - 'traefik.http.routers.webserver-web-secure.rule=Host(`status.golemstats.com`)'
        - 'traefik.http.routers.webserver-web-secure.tls=true'
        - 'traefik.http.routers.webserver-web-secure.entrypoints=web-secure'
      replicas: 3
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - swarm-example
  redis:
    image: 'redis:alpine'
    expose:
      - '6379'
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - swarm-example
  celery:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    image: celery_wtf:latest
    volumes:
      - './stats-monitor:/stats-monitor/'
      - './wait-for-it.sh:/wait-for-it.sh'
      - './check_yagna.sh:/check_yagna.sh'
    env_file:
      - ./.envs/.django
    depends_on:
      - redis
      - postgres
      - webserver
    healthcheck:
      test: /check_yagna.sh || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    deploy:
      replicas: 3
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - swarm-example
  celery_beat:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    image: celery_beat:latest
    command: celery -A core beat -l INFO
    volumes:
      - './stats-monitor:/stats-monitor/'
      - './wait-for-it.sh:/wait-for-it.sh'
    env_file:
      - ./.envs/.django
    depends_on:
      - redis
      - postgres
      - webserver
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    networks:
      - swarm-example
  postgres:
    image: postgres
    build:
      context: .
      dockerfile: compose/postgres/Dockerfile
    env_file:
      - ./.envs/.db
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    networks:
      - swarm-example
networks:
  swarm-example:
    driver: overlay
