# Generated by Django 3.2.2 on 2021-05-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResponseTime', models.DurationField()),
                ('Url', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=50)),
                ('ResponseCode', models.CharField(max_length=3)),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
